name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - feature/azure-storage
    paths:
      - 'client/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - feature/azure-storage
    paths:
      - 'client/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          NODE_VERSION: 20.11.1
          NPM_CONFIG_LEGACY_PEER_DEPS: true
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E8C92D0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "client" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/client/browser" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      # - name: Create output directory
      #   run: mkdir -p dist/client/browser
      # - name: Copy routes.json to build output directory
      #   run: cp client/routes.json dist/client/browser

  
  cleanup:
    runs-on: ubuntu-latest
    needs: build_and_deploy_job
    steps:
      - name: Clean up artifacts
        uses: actions/checkout@v4
        with:
          clean: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E8C92D0F }}
          action: "close"
